### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{ "username": "removarr", "password": "&n*zQt$G12h&cQ4K" }

> {%
    client.global.set("token", response.body.access_token);
%}

### OpenAPI spec
GET http://localhost:3000/api/openapi.json
Authorization: Bearer {{token}}
